#!/bin/bash

curl -O https://archive.apache.org/dist/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz

tar xvf spark-3.2.0-bin-hadoop3.2.tgz

mkdir .spark

mv spark-3.2.0-bin-hadoop3.2/ .spark

exec "$@"
