#!/bin/bash

curl -O https://archive.apache.org/dist/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz

tar xvf spark-3.2.0-bin-hadoop3.2.tgz

sudo mv spark-3.2.0-bin-hadoop3.2/ /opt/spark

echo "export SPARK_HOME=/opt/spark" >> ~/.bashrc
echo "export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin" >> ~/.bashrc

source ~/.bashrc

exec "$@"
